version: '3'
services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: steve_mythtv_1
      APP_PORT: 3000
  mythbackend:
    build: .
    environment:
      - CONFIG_MODE=1
    volumes:
      - config:/home/mythtv:nocopy
      - data:/var/lib/mysql:nocopy
      - media:/var/lib/mythtv:nocopy
      - ./shared:/shared
    hostname: mythbackend
    network_mode: "host"
volumes:
  config:
  data:
  media:
