version: '3.5'

services:
  app_proxy:
    environment:
      APP_HOST: steve-tvheadend
      APP_PORT: 9981

  server:
   image: lscr.io/linuxserver/tvheadend:latest
    container_name: tvheadend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - RUN_OPTS= #optional
    volumes:
      - /path/to/data:/config
      - /path/to/recordings:/recordings
    ports:
      - 9981:9981
      - 9982:9982
 
    restart: unless-stopped
